### ISSUE TITLE
OAuth 2 support

### ISSUE THREAD

**Issue by ipartola** [rdio/rdio-python#6]
According to http://blog.rdio.com/developers/2015/06/oauth-20-launch.html OAuth 1 support will be dropped on June 30th 2015. This will render this official client useless. Are there any plans to provide an official OAuth2 API client?

**Comment by meson10** [comment]
+1

**Comment by rlvoyer** [comment]
+1

**Comment by rknLA** [comment]
I'm pretty sure this is on the roadmap, but in the meantime, I'd recommend using [oauthlib](https://pypi.python.org/pypi/oauthlib) to create and manage an [OAuth 2 Client](https://oauthlib.readthedocs.org/en/latest/oauth2/clients/client.html).

**Comment by NJAldwin** [comment]
+1

**Comment by jmullan** [comment]
Should be working now since https://github.com/rdio/rdio-python/pull/7 landed. You will probably have to reauthenticate. Please open new issues if you have any trouble.
